### ISSUE TITLE
Error "This authorization code has been used."

### ISSUE THREAD

**Issue by vojtasvoboda** [ebussola/octobercms-user-facebook#4]
Hello,

I'm just trying your plugin, but I always get error "This authorization code has been used.".

When I use `console.log(response.status)` in JS part of plugin, it gives me "connected", so JS auth works well. Then I tried:

```
Log::info(json_encode($fbJs->getSession()));
```

at FacebookSession->onLoginWithFacebook() and it returns `null`. And then I received this error above "This authorization code has been used.".

Can you help me please?

**Comment by shina** [comment]
Hello vojtasvoboda, I did a fresh install now and it is working.

By your description, your problem seems to be on keeping the session alive.
The facebook lib (php) uses the same cookie used by the javascript lib to recover the session and identify the user.

**Comment by vojtasvoboda** [comment]
Thanks @shina for the quick reply! What does this mean: "problem is on keeping the session alive"? I tried to clean Facebook cookie (prefixed by `fbsr`) but it didn't help. Is there some special setting at Facebook Dev pages? I just created new Web Application, select Facebook login type, activate it and copy App ID and App Secret - nothing else.

**Comment by shina** [comment]
Sorry for the late reply. There is no special setting at facebook dev pages. The Web Application is the right choice.

I hope you already solved it by yourself, however if you don't:

The problem seems to be (to me) the user session. Check if your application is keeping the same session while the user navigate the site.

If it is changing every time, something is wrong with your server configuration.
